# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_train_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_train_service.proto',
  package='example',
  syntax='proto3',
  serialized_pb=_b('\n\x19image_train_service.proto\x12\x07\x65xample\"i\n\x0cTrainRequest\x12\x10\n\x08train_no\x18\x01 \x01(\t\x12\x12\n\ntrain_step\x18\x02 \x01(\x03\x12\x1a\n\x12train_test_percent\x18\x03 \x01(\x05\x12\x17\n\x0ftrain_shard_num\x18\x04 \x01(\x05\"-\n\rTrainResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2J\n\x0cTrainService\x12:\n\x07\x44oTrain\x12\x15.example.TrainRequest\x1a\x16.example.TrainResponse\"\x00\x42\'\n\x17\x65\x64u.nudt.das.image.grpcB\nTrainProtoP\x01\x62\x06proto3')
)




_TRAINREQUEST = _descriptor.Descriptor(
  name='TrainRequest',
  full_name='example.TrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_no', full_name='example.TrainRequest.train_no', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_step', full_name='example.TrainRequest.train_step', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_test_percent', full_name='example.TrainRequest.train_test_percent', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_shard_num', full_name='example.TrainRequest.train_shard_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=143,
)


_TRAINRESPONSE = _descriptor.Descriptor(
  name='TrainResponse',
  full_name='example.TrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='example.TrainResponse.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='example.TrainResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['TrainRequest'] = _TRAINREQUEST
DESCRIPTOR.message_types_by_name['TrainResponse'] = _TRAINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRAINREQUEST,
  __module__ = 'image_train_service_pb2'
  # @@protoc_insertion_point(class_scope:example.TrainRequest)
  ))
_sym_db.RegisterMessage(TrainRequest)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), dict(
  DESCRIPTOR = _TRAINRESPONSE,
  __module__ = 'image_train_service_pb2'
  # @@protoc_insertion_point(class_scope:example.TrainResponse)
  ))
_sym_db.RegisterMessage(TrainResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027edu.nudt.das.image.grpcB\nTrainProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class TrainServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.DoTrain = channel.unary_unary(
          '/example.TrainService/DoTrain',
          request_serializer=TrainRequest.SerializeToString,
          response_deserializer=TrainResponse.FromString,
          )


  class TrainServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def DoTrain(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_TrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'DoTrain': grpc.unary_unary_rpc_method_handler(
            servicer.DoTrain,
            request_deserializer=TrainRequest.FromString,
            response_serializer=TrainResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'example.TrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaTrainServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def DoTrain(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaTrainServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def DoTrain(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    DoTrain.future = None


  def beta_create_TrainService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('example.TrainService', 'DoTrain'): TrainRequest.FromString,
    }
    response_serializers = {
      ('example.TrainService', 'DoTrain'): TrainResponse.SerializeToString,
    }
    method_implementations = {
      ('example.TrainService', 'DoTrain'): face_utilities.unary_unary_inline(servicer.DoTrain),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_TrainService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('example.TrainService', 'DoTrain'): TrainRequest.SerializeToString,
    }
    response_deserializers = {
      ('example.TrainService', 'DoTrain'): TrainResponse.FromString,
    }
    cardinalities = {
      'DoTrain': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'example.TrainService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
