# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_train_service_pb2 as image__train__service__pb2


class TrainServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoTrain = channel.unary_unary(
        '/example.TrainService/DoTrain',
        request_serializer=image__train__service__pb2.TrainRequest.SerializeToString,
        response_deserializer=image__train__service__pb2.TrainResponse.FromString,
        )


class TrainServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoTrain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrainServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoTrain': grpc.unary_unary_rpc_method_handler(
          servicer.DoTrain,
          request_deserializer=image__train__service__pb2.TrainRequest.FromString,
          response_serializer=image__train__service__pb2.TrainResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'example.TrainService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
